# Generated by Django 5.1.1 on 2024-11-29 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='employees',
        ),
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
