# Generated by Django 5.1.1 on 2024-11-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_branch_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='created_by',
        ),
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='branch_images/'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
