# Generated by Django 5.1.1 on 2024-11-22 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedcomments', '0006_feedback_user_avatar_url_alter_feedback_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_avatar_url',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
