# Generated by Django 5.1.1 on 2024-12-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedcomments', '0007_alter_feedback_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-timestamp']},
        ),
    ]
